version: '3.3'

services:
  tracks_api:
    build: .
    ports:
      - 3001:3000
    environment:
      VIRTUAL_HOST: tracks-api.aqelia.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: tracks-api.aqelia.com

networks:
  default:
    external:
      name: reverse-proxy
